#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Regain_v2.Resource", IsApplication=true)]

namespace Regain_v2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int IntroText = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int black = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int blue = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int green = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int red = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int DefaultIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int exercise01 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int exercise02 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int exercise03 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int exercise04 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int exercise05 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int exercise06 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int green_btn_200 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int green_btn_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int green_out_200 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int i_agility01 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int i_agility02 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int i_agility03 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int i_agility04 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int i_agility05 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int i_agility06 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int i_balance01 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int i_balance02 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int i_balance03 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int i_balance04 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int i_balance05 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int i_functional01 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int i_functional02 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int i_functional03 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int i_functional04 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int i_functional05 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int i_functional06 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int i_stretching01 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int i_stretching02 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int i_stretching03 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int i_stretching04 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int i_stretching05 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int i_stretching06 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int i_warm_up01 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int i_warm_up02 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int i_warm_up03 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int i_warm_up04 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Icon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int info = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int instruction_logo = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int SmartDesLogo = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int splash = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int test = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int UoN_Logo = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int v_agility01 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int v_agility02 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int v_agility03 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int v_agility04 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int v_agility05 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int v_agility06 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int v_balance01 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int v_balance02 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int v_balance03 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int v_balance04 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int v_balance05 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int v_functional01 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int v_functional02 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int v_functional03 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int v_functional04 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int v_functional05 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int v_functional06 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int v_stretching01 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int v_stretching02 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int v_stretching03 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int v_stretching04 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int v_stretching05 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int v_stretching06 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int v_warm_up01 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int v_warm_up02 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int v_warm_up03 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int v_warm_up04 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int warm_up_main = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int welcome_bg = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int white_btn_200 = 2130837579;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int contGridLayout = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int contGroupGrid = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int contImgBack = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int contImgIcon = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int contImgInfo = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int contTxtDebug = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int infoImgBack = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int infoImgIcon = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int infoImgInfo = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int infoTxtAbout = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int infoTxtInfo = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int infoTxtQuote = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int infoTxtSmart = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int mainButBack = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int mainButNext = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int mainButSkip = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int mainTxtIntr = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int mainTxtProg = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int mainTxtWelc = 2131230734;
			
			// aapt resource value: 0x7f080017
			public const int setButDefault = 2131230743;
			
			// aapt resource value: 0x7f080015
			public const int setGridLayout = 2131230741;
			
			// aapt resource value: 0x7f080013
			public const int setImgBack = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int setImgInfo = 2131230740;
			
			// aapt resource value: 0x7f080016
			public const int setTxtDebug = 2131230742;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Content = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int Information = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int MaedaQuote = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Password = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int SmartDesign = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int SplashScreen = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
