#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Regain_v2._1.Resource", IsApplication=true)]

namespace Regain_v2._1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060001
			public const int ExerciseName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int IntroText = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int black = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int blue = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int green = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int red = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int DefaultIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int green_btn_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int info = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int instruction_logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int SmartDesLogo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int UoN_Logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int welcome_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int BackButton = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int NextButton = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int SkipButton = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int aboutText = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int contentInfo = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int headerBack = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int headerIcon = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int headerInfo = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int quoteText = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int scrollview = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int setGrid = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int smartDesign = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int text00 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int text01 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int txtIntro = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Content = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int Information = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int MaedaQuote = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Password = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int SmartDesign = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
